# H2 in-memory
spring.datasource.url=jdbc:h2:mem:cinema;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.access.secret=${JWT_ACCESS_SECRET}
jwt.access.expiration-ms=900000
jwt.refresh.secret=${JWT_REFRESH_SECRET}
jwt.refresh.expiration-ms=604800000


server.servlet.session.cookie.same-site=lax
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:server3388.jks
server.ssl.key-store-password=Spass3388
server.ssl.key-store-type=JKS
server.ssl.key-alias=server3388
